import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import linksRouter from "./links";
import productsRouter from "./products";
import postsRouter from "./posts";
import analyticsRouter from "./analytics";
import openaiRouter from "./openai";
import authRouter from "./auth";
import subscriptionRouter from "./subscription";
import walletRouter from "./wallet";
import withdrawalsRouter from "./withdrawals";
import aiCreditsRouter from "./ai_credits";
import teamsRouter from "./teams";
import socialAccountsRouter from "./social_accounts";
import uploadsRouter from "./uploads";
import adminRouter from "./admin";
import aiToolsRouter from "./ai_tools";
import storageRouter from "./storage";
import paystackRouter from "./paystack";
import aiWorkspaceRouter from "./ai_workspace";
import notificationsRouter from "./notifications";
import adsRouter from "./ads";
import marketplaceRouter from "./marketplace";
import messagingRouter from "./messaging";
import referralsRouter from "./referrals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(linksRouter);
router.use(productsRouter);
router.use(postsRouter);
router.use(analyticsRouter);
router.use(openaiRouter);
router.use(subscriptionRouter);
router.use(walletRouter);
router.use(withdrawalsRouter);
router.use(aiCreditsRouter);
router.use(teamsRouter);
router.use(socialAccountsRouter);
router.use(uploadsRouter);
router.use(adminRouter);
router.use(aiToolsRouter);
router.use(storageRouter);
router.use(paystackRouter);
router.use(aiWorkspaceRouter);
router.use(notificationsRouter);
router.use(adsRouter);
router.use(marketplaceRouter);
router.use(messagingRouter);
router.use(referralsRouter);

export default router;
